all:
  children:
    mgr:
      hosts:
        mgr1:
          ansible_host: 1.1.1.1
          ansible_user: admin
          ansible_python_interpreter: /usr/bin/python3
    workers:
      hosts:
        worker1:
          ansible_host: 11.1.1.2
          ansible_user: admin
          ansible_python_interpreter: /usr/bin/python3
        worker2:
          ansible_host: 1.1.1.3
          ansible_user: admin
          ansible_python_interpreter: /usr/bin/python3
        worker3:
          ansible_host: 1.1.1.4
          ansible_user: admin
          ansible_python_interpreter: /usr/bin/python3
