---

- name: Installing packages
  apt:
    name:     
      - python-setuptools
      - python-pip
    state: present

- name: Installing dependencies
  pip:
    name: "{{ docker_compose_pip_version }}"

- name: Installing docker compose
  pip:
    name: docker-compose
    version: "{{ docker_compose_version if docker_compose_version else omit }}"
    state: present
