---

- name: Installing packages
  apt:
    name:     
      - python3-setuptools
      - python3-pip
    state: present

- name: Installing docker compose
  pip:
    name: docker-compose
    version: "{{ docker_compose_version if docker_compose_version else omit }}"
    state: present
